title: Induja Shankar # your name (or website title) here
logo: "https://picsum.photos/seed/picsum/200/300" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Pretend I wrote something amazing here. 
  <br><br>
  Don't stop pretending, okay?
  <br><br>
  <a href="https://www.linkedin.com/in/indujashankar/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
